Repository openwdl/wdl, pull requests merged in 2020-02, with the labels that each got.

#354 [minor] add missing paren in read_map example
  versions/development/SPEC.md
Labels: No Vote Needed, docs

#355 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: community

#257 Rework of 'Scopes' and 'Variable Resolution' Sections
  versions/development/SPEC.md
Labels: clarification
