Repository openwdl/wdl, pull requests merged in 2020-06, with the labels that each got.

#374 fixed typos
  versions/development/SPEC.md
Labels: No Vote Needed

#360 Add document with differences between WDL versions
  versions/Differences.md
Labels: No Vote Needed, clarification, docs

#375 Add Draft2 ANTLR grammar
  CHANGELOG.md
  versions/draft-2/parsers/antlr4/WdlDraft2Lexer.g4
  versions/draft-2/parsers/antlr4/WdlDraft2Parser.g4
Labels: No Vote Needed, enhancement

#376 Updates to V1 ANTLR lexer/parser
  CHANGELOG.md
  versions/1.0/parsers/antlr4/WdlLexer.g4
  versions/1.0/parsers/antlr4/WdlParser.g4
  versions/1.0/parsers/antlr4/WdlV1Lexer.g4
  versions/1.0/parsers/antlr4/WdlV1Parser.g4
Labels: No Vote Needed, enhancement
